In [90]:
import pandas as pd
from pyod.models.abod import ABOD

from Outlier_Detection.sort_date import sort_date
from Outlier_Detection.remove_nan import remove_nan

import matplotlib.pyplot as plt
import numpy as np

In [91]:
file_name = 'C:/Users/interXlab01/Desktop/DATA/Hanju/CSV/1/201805.csv'
df = pd.read_csv(file_name,low_memory=False, index_col=None, encoding='utf-8')

df = remove_nan(sort_date(df))

line1_1 = df[df['작업라인']=='전자교반 1라인 1호기']
line1_1 = line1_1[line1_1['품명']=='IG CARRIER-RR RH']
plot_data = line1_1

In [94]:
from pyod.models.abod import ABOD

data = plot_data[plot_data['작업라인']=='전자교반 1라인 1호기']
del data['금형코드']
del data['전자교반 가동시간']
del data['생산수량']

data = data[data['품명']=='IG CARRIER-RR RH']
outlier_tbl = pd.DataFrame(columns=['Working no','Variable name','Value','Algorithm name','date'])
n = 0 #column number


for i in data.dtypes:
    if i == np.int64 or i == np.float64 : # 정수형만 outlier 제거
            print(data.iloc[:,n])
            # nan값 채우기
            data.iloc[:,n] = data.iloc[:,n].interpolate(method='linear', order=1, limit_direction='both')
 
            #-------------------------------------------
            
            clf = ABOD()
            #clf.fit(data.iloc[:,n].to_numpy().reshape(-1,1))
            #clf.fit_predict(data.iloc[:,n].to_numpy().reshape(-1,1))
            
            #-------------------------------------------
            

    n+=1

118581    688
118577    688
118573    688
118565    688
118559    689
         ...
43        686
29        687
17        687
10        688
1         689
Name: 저속구간속도, Length: 10115, dtype: int64
118581     66.0
118577     64.0
118573     64.0
118565     63.0
118559     62.0
          ...
43        102.0
29        101.0
17        101.0
10        100.0
1         100.0
Name: 용탕온도, Length: 10115, dtype: float64
118581    101
118577    100
118573     99
118565     99
118559    100
         ...
43         90
29         90
17         89
10         90
1          90
Name: 가동보온로, Length: 10115, dtype: int64
118581    85.0
118577    95.0
118573    94.0
118565    87.0
118559    91.0
          ...
43        95.0
29        89.0
17        86.0
10        91.0
1         90.0
Name: 용탕량, Length: 10115, dtype: float64
118581    171.0
118577    171.0
118573    326.0
118565    336.0
118559    339.0
          ...
43        302.0
29        327.0
17        302.0
10        329.0
1         303.0
Name: 주조(증압)압력, Length: 10115, dtype: float64
118581    61
118577    56
118573    52
118565    53
118559    51
          ..
43        44
29        36
17        39
10        40
1         40
Name: 비스켓 두께, Length: 10115, dtype: int64
118581     24
118577     24
118573     24
118565     24
118559     24
         ...
43        120
29        120
17        119
10        118
1         118
Name: 상금형온도1, Length: 10115, dtype: int64
118581     22
118577     22
118573     22
118565     23
118559     23
         ...
43        122
29        122
17        121
10        120
1         120
Name: 상금형온도2, Length: 10115, dtype: int64
118581     25.0
118577     24.0
118573     24.0
118565     25.0
118559     26.0
          ...
43        142.0
29        125.0
17        134.0
10        137.0
1         137.0
Name: 상금형온도3, Length: 10115, dtype: float64
118581    24
118577    24
118573    24
118565    24
118559    24
          ..
43        28
29        29
17        29
10        29
1         29
Name: 상금형온도4, Length: 10115, dtype: int64
118581    23
118577    24
118573    23
118565    24
118559    23
          ..
43        29
29        29
17        29
10        29
1         29
Name: 상금형온도5, Length: 10115, dtype: int64
118581     20
118577     73
118573     99
118565    100
118559    126
         ...
43        133
29        127
17        127
10        129
1         128
Name: 하금형온도1, Length: 10115, dtype: int64
118581     41.0
118577     96.0
118573    125.0
118565    128.0
118559    149.0
          ...
43        167.0
29        189.0
17        157.0
10        159.0
1         161.0
Name: 하금형온도2, Length: 10115, dtype: float64
118581    25.0
118577    25.0
118573    24.0
118565    25.0
118559    25.0
          ...
43        95.0
29        96.0
17        95.0
10        94.0
1         94.0
Name: 하금형온도3, Length: 10115, dtype: float64
118581    45
118577    44
118573    45
118565    45
118559    45
          ..
43        32
29        32
17        32
10        32
1         32
Name: 하금형온도4, Length: 10115, dtype: int64
118581    365
118577    397
118573    424
118565    445
118559    459
         ...
43        473
29        450
17        461
10        467
1         452
Name: 슬리브온도, Length: 10115, dtype: int64
118581    159.0
118577    160.0
118573    161.0
118565    162.0
118559    164.0
          ...
43        157.0
29        157.0
17        157.0
10        156.0
1         156.0
Name: 형체력, Length: 10115, dtype: float64
118581    20
118577    20
118573    20
118565    20
118559    20
          ..
43        21
29        21
17        22
10        22
1         22
Name: 냉각수 온도, Length: 10115, dtype: int64
118581    44
118577    55
118573    59
118565    44
118559    63
          ..
43        69
29        68
17        74
10        73
1         73
Name: 설비가동 CT, Length: 10115, dtype: int64
118581     42
118577     53
118573     58
118565     43
118559     62
         ...
43        124
29         67
17        128
10        128
1         128
Name: 제품생산 CT, Length: 10115, dtype: int64

In [82]:
from sklearn.cluster import DBSCAN


data = plot_data[plot_data['작업라인']=='전자교반 1라인 1호기']
del data['금형코드']
del data['전자교반 가동시간']
del data['생산수량']

data = data[data['품명']=='IG CARRIER-RR RH']
outlier_tbl = pd.DataFrame(columns=['Working no','Variable name','Value','Algorithm name','date'])
n = 0 #column number


for i in data.dtypes:
    if i == np.int64 or i == np.float64 : # 정수형만 outlier 제거
        #print(data.iloc[:,n])
        # nan값 채우기
        data.iloc[:,n] = data.iloc[:,n].interpolate(method='linear', order=1, limit_direction='both')

        #-------------------------------------------


        outlier_detection = DBSCAN()
        clusters = outlier_detection.fit_predict(data.iloc[:,n].to_numpy().reshape(-1,1))
        indx = np.where(clusters==-1)
        #print(indx)

        for j in indx[0]:
            outlier_tbl = outlier_tbl.append({'Working no':data.iloc[j,:].date,'Variable name':data.columns[n],'Value':data.iat[j,n],'Algorithm name':'DBScan','date':data.iloc[j,:].date}, ignore_index=True)


        #-------------------------------------------
            

    n+=1

In [83]:
outlier_tbl[outlier_tbl['Variable name']=='상금형온도2']

             Working no Variable name Value Algorithm name                date
289 2018-05-01 19:53:26        상금형온도2    22         DBSCAN 2018-05-01 19:53:26
290 2018-05-01 19:55:20        상금형온도2    22         DBSCAN 2018-05-01 19:55:20
291 2018-05-01 19:57:22        상금형온도2    22         DBSCAN 2018-05-01 19:57:22
292 2018-05-01 20:00:21        상금형온도2    23         DBSCAN 2018-05-01 20:00:21
293 2018-05-01 20:02:35        상금형온도2    23         DBSCAN 2018-05-01 20:02:35
..                  ...           ...   ...            ...                 ...
394 2018-05-31 07:55:29        상금형온도2    48         DBSCAN 2018-05-31 07:55:29
395 2018-05-31 07:58:01        상금형온도2    50         DBSCAN 2018-05-31 07:58:01
396 2018-05-31 08:00:03        상금형온도2    55         DBSCAN 2018-05-31 08:00:03
397 2018-05-31 08:02:01        상금형온도2    59         DBSCAN 2018-05-31 08:02:01
398 2018-05-31 08:28:02        상금형온도2    89         DBSCAN 2018-05-31 08:28:02

[110 rows x 5 columns]